modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/ppVon/ultimate-cobblemon-progression/issues"
license = "MIT License"

[[mods]]
modId = "ultimate_cobblemon_progression"
version = "${version}"
displayName = "Ultimate Cobblemon Progression"
authors = "ppVon"
description = '''
Adds game-like progression to Cobblemon
'''
#logoFile = ""

[[mixins]]
config="ucp.mixins.json"

[[dependencies.ultimate_cobblemon_progression]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.ultimate_cobblemon_progression]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ultimate_cobblemon_progression]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.0,)"
ordering = "AFTER"
side = "BOTH"
